name: Integrate

on:
  pull_request:
    branches: [ develop ]

jobs:
  run-unit-tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.5

      - run: npm ci
      - run: npm run test:unit
  
  run-e2e-tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: npm run test:e2e:CI_CD