name: Integrate

on:
  pull_request:
    branches: [ develop ]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.15.5

      - run: npm ci
      - run: npm run test:unit
  
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: "sudo docker-compose \
            -f docker/docker-compose.yml \
            -f docker/docker-compose.e2e.yml \
            --env-file .env.example \
            up \
            --abort-on-container-exit"